# Enable 256 color support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Enable clipboard
set -g set-clipboard on

# Tokyo Night Moon theme colors
thm_bg="#222436"
thm_fg="#c8d3f5"
thm_cyan="#86e1fc"
thm_black="#1b1d2b"
thm_gray="#3a3f5a"
thm_magenta="#c099ff"
thm_pink="#ff757f"
thm_red="#ff757f"
thm_green="#c3e88d"
thm_yellow="#ffc777"
thm_blue="#82aaff"
thm_orange="#ff9e64"
thm_black4="#444a73"

# Status bar settings
set -g status "on"
set -g status-position "bottom"
set -g status-bg "${thm_bg}"
set -g status-justify "centre"
set -g status-left-length "100"
set -g status-right-length "100"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-activity-style "fg=${thm_fg},bg=${thm_bg},none"
set -g window-status-separator "#[fg=${thm_blue},bg=${thm_bg}]| "
set -g window-status-style "fg=${thm_fg},bg=${thm_bg},none"

# Statusline - current window
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg}]#I: #[fg=${thm_magenta},bg=${thm_bg}](✓) #[fg=${thm_cyan},bg=${thm_bg}]#W #[fg=${thm_magenta},bg=${thm_bg}]"

# Statusline - other windows
set -g window-status-format "#[fg=${thm_blue},bg=${thm_bg}]#I: #[fg=${thm_fg},bg=${thm_bg}]#W "

# Statusline - right side
set -g status-right "#[fg=${thm_bg},bg=${thm_yellow},nobold,nounderscore,noitalics] #(echo $USER) #[fg=${thm_bg},bg=${thm_green},nobold,nounderscore,noitalics] #H "

# Statusline - left side (empty)
set -g status-left "#[bg=${thm_blue},fg=${thm_bg}]#S "

# Modes
set -g clock-mode-colour "${thm_blue}"
set -g mode-style "fg=${thm_blue} bg=${thm_black4} bold"

# Change from 0 based to 1 based because keyboard layout
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# History and reload
set-option -g history-limit 100000
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
